name: Deploy to ACR and AKS

on:
  push:
    branches: [ youtube-eks-deploy ]

env:
  ACR_NAME: flaskapp1
  AKS_CLUSTER_NAME: Kubernetes-demo
  AZURE_REGION: eastus

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Login to Azure Container Registry
    #   run: |
    #     az ad sp create-for-rbac --name "my-github-actions" --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} --sdk-auth
    #     az acr login --name $ACR_NAME

    - name: Azure login
      uses: azure/login@v2
      with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build, tag, and push image to ACR
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t $ACR_NAME.azurecr.io/myapp:$IMAGE_TAG -f docker/Dockerfile .
        docker push $ACR_NAME.azurecr.io/myapp:$IMAGE_TAG

    - name: Set up kubectl
      run: az aks get-credentials --resource-group myResourceGroup --name $AKS_CLUSTER_NAME

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/myapp myapp=$ACR_NAME.azurecr.io/myapp:$IMAGE_TAG
